[server]
headless = true
enableCORS = false
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1256D3"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F9FC"
textColor = "#0F1B2D"
